# Generated by Django 5.1.6 on 2025-04-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
