# Generated by Django 5.1.6 on 2025-04-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_product_product_image_product_product_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image_5',
        ),
    ]
