# Generated by Django 5.1.6 on 2025-04-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_product_product_image_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
