# Generated by Django 5.1.6 on 2025-04-24 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_phoneotp_customuser_is_phone_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
    ]
