# Generated by Django 5.2 on 2025-05-12 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_unit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
