# Generated by Django 5.2 on 2025-05-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_inventory_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('in', 'In Stock'), ('running_out', 'Running Out'), ('out_of_stock', 'Out of Stock')], default='in', max_length=20),
        ),
    ]
