# Generated by Django 5.2 on 2025-05-12 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_inventory_expiry_date_inventory_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
