# Generated by Django 5.2.1 on 2025-05-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_product_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='background_img',
            field=models.ImageField(default='background image', upload_to='category/'),
        ),
    ]
