# Generated by Django 5.2.1 on 2025-05-20 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inventory',
        ),
    ]
