# Generated by Django 5.2.1 on 2025-05-20 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_product_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
