# Generated by Django 5.2.1 on 2025-05-20 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_delete_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products_base_unit', to='users.unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_in_base_unit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in', 'In Stock'), ('running_out', 'Running Out'), ('out_of_stock', 'Out of Stock')], default='in', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='threshold_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
