# Generated by Django 5.2.1 on 2025-05-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_product_base_unit_product_quantity_in_base_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='staff',
            name='is_inventory_manager',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='is_order_manager',
        ),
        migrations.AddField(
            model_name='staff',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='roles',
            field=models.ManyToManyField(related_name='staff_members', to='users.role'),
        ),
    ]
