# Generated by Django 5.2.1 on 2025-05-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_role_remove_staff_is_inventory_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='SAP_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
