# Generated by Django 5.2.1 on 2025-05-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_product_sap_code_product_brand_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Enter discount % (e.g. 10 for 10%)', max_digits=5)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='flash_sales', to='users.categories')),
                ('products', models.ManyToManyField(blank=True, related_name='flash_sales', to='users.product')),
            ],
        ),
    ]
