# Generated by Django 5.2.1 on 2025-05-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_remove_flashsale_description_flashsale_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsale',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='flash_sale_backgrounds/'),
        ),
    ]
