# Generated by Django 5.2.1 on 2025-06-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_customuser_email_alter_customuser_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='city',
            new_name='area',
        ),
        migrations.AddField(
            model_name='customuser',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
