# Generated by Django 5.2.1 on 2025-06-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_rename_city_customuser_area_customuser_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='SAP_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
