# Generated by Django 5.2.1 on 2025-06-20 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_payment_method_order_payment_type'),
        ('users', '0041_promocode_promocodeusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDriverAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignment', to='orders.order')),
            ],
        ),
    ]
