# Generated by Django 5.2.1 on 2025-06-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_orderdriverassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
