# Generated by Django 5.2.1 on 2025-06-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_customuser_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='base_unit',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='quantity_in_base_unit',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='status',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='threshold_quantity',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
