# Generated by Django 5.2.1 on 2025-06-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_customuser_latitude_customuser_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrating',
            name='review',
        ),
    ]
