# Generated by Django 5.2.1 on 2025-07-07 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_onboardingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='pack_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pack_unit_variants', to='users.unit'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='unit_weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='units_per_pack',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='selling_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_unit_variants', to='users.unit'),
        ),
    ]
