# Generated by Django 5.2.1 on 2025-07-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_productvariant_pack_unit_productvariant_unit_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
