# Generated by Django 5.2.1 on 2025-07-08 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_product_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='pack_unit',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='unit_weight',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='units_per_pack',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='selling_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.unit'),
        ),
    ]
