# Generated by Django 5.2.1 on 2025-07-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_remove_product_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
