# Generated by Django 5.2.1 on 2025-08-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['is_active'], name='users_devic_is_acti_2e47a5_idx'),
        ),
    ]
