# Generated by Django 5.2.1 on 2025-09-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_devicetoken_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='province',
            field=models.CharField(blank=True, choices=[('Riyadh', 'Riyadh'), ('Makkah', 'Makkah'), ('Madinah', 'Madinah'), ('Qassim', 'Qassim'), ('Eastern Province', 'Eastern Province'), ('Asir', 'Asir'), ('Tabuk', 'Tabuk'), ('Hail', 'Hail'), ('Northern Borders', 'Northern Borders'), ('Jizan', 'Jizan'), ('Najran', 'Najran'), ('Al-Bahah', 'Al-Bahah'), ('Al-Jawf', 'Al-Jawf')], max_length=50, null=True),
        ),
    ]
