# Generated by Django 5.2.1 on 2026-02-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_dashboardbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardbanner',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='flashsale',
            name='is_active',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
