# Generated by Django 5.2.1 on 2025-06-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_functionality', '0003_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
