# Generated by Django 5.2.1 on 2025-06-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_functionality', '0006_address_latitude_address_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('Other', 'Other')], default='home', max_length=10),
        ),
    ]
