# Generated by Django 5.2.1 on 2025-09-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_is_deleted_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_including_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
